# Generated by Django 3.1.3 on 2021-01-01 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('land_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=3)),
                ('capcity', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='airport.airport')),
                ('orgin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgin', to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.flight')),
            ],
        ),
    ]
