# Generated by Django 3.1.3 on 2021-01-02 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'فرودگاه', 'verbose_name_plural': 'فرودگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'پرواز', 'verbose_name_plural': 'پرواز ها'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'خدمه', 'verbose_name_plural': 'خدمه ها'},
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=60, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=60, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='capcity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='airport.airport', verbose_name='مقصد'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ساعت و تاریخ پرواز'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='land_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='  ساعت و تاریخ فرود'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='orgin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgin', to='airport.airport', verbose_name='مبدا'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('C', 'کنسل'), ('D', 'تاخیر'), ('I', 'حادثه'), ('O', 'Ok')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.IntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('U', 'Undefined')], max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=60, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('C', 'کاپیتان'), ('M', 'مهماندار'), ('K', 'کمک خلبان')], max_length=1, verbose_name='نقش'),
        ),
    ]
