# Generated by Django 3.1.3 on 2021-01-08 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_auto_20210102_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('U', 'Undefined')], max_length=1, verbose_name='جنسیت')),
                ('email', models.EmailField(max_length=254)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='airport.flight')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.passenger')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافرها',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('F', 'First class'), ('R', 'regular'), ('B', 'Bisiness')], max_length=1, verbose_name='جنسیت')),
                ('price', models.PositiveIntegerField()),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='airport.flight')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='airport.passenger')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط ها',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('job', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('U', 'Undefined')], max_length=1, verbose_name='جنسیت')),
                ('pay', models.IntegerField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airport')),
            ],
            options={
                'verbose_name': 'کارمندان',
                'verbose_name_plural': 'کارمندان ها',
            },
        ),
    ]
