# Generated by Django 3.1.3 on 2021-01-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_employee_passenger_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airport.employee'),
        ),
    ]
